### ISSUE TITLE
problem with ensuremath construct

### ISSUE THREAD

**Issue by fiolj** [phfaist/pylatexenc#100]
Hi, pylatexenc 2.10 is failing with the construct:

`LatexNodes2Text().latex_to_text(unicode_to_latex(LatexNodes2Text().latex_to_text(r"$\pm$")))`

giving  empty strings.
The conversion:
    
    `LatexNodes2Text().latex_to_text(r"$\pm$")`

gives the expected result:
     `'±'`

and the conversion to latex:
     `unicode_to_latex('±')`
seems to be ok also:
     `'\\ensuremath{\\pm}'`

but the last conversion:
   `LatexNodes2Text().latex_to_text('\\ensuremath{\\pm}')`
 fails, producing the empty string

**Comment by phfaist** [comment]
This appears to work in the new `pylatexenc` v3 alpha:
```
> poetry run latex2text -c '\ensuremath{\pm}'
±
```
Feel free to reopen if the problem persists.
