### ISSUE TITLE
Is there a way to automatically insert multiplication sign?

### ISSUE THREAD

**Issue by Lizn-zn** [phfaist/pylatexenc#106]
Thanks for the nice tool. I am currently using your project to convert LaTeX code into plain text and wonder to know if there is a way to automatically convert implicit multiplication into explicit multiplication signs, e.g. `$(a+b)(b+c)$ -> (a+b)*(b+c). `

Thanks again,

**Comment by phfaist** [comment]
I could imagine ways to achieve this by defining '(' as a latex specials (see `pylatexenc.macrospec.SpecialsSpec`) and using a custom parser (group parser with parentheses delimiters) to get the entire argument of the parentheses. Then you could detect two consecutive parentheses group nodes and insert multiplication signs, or something like that. There's no out-of-the-box way of achieving this, though.
