### ISSUE TITLE
latex2text is removing macroname from the latext- text

### ISSUE THREAD

**Issue by chetankabra** [phfaist/pylatexenc#12]
`encoder = LatexNodes2Text(keep_inline_math=True, keep_comments=True)`
`print encoder.latex_to_text(r'Global well-posedness for the mass-critical stochastic nonlinear Schr\"{o}dinger equation on $\mathbb{R}$: small initial data')
`
I have used above code to decode Latex command and I only want the latex accent command to be converted to plain text. 

but Latex is removing latex macro from the output.
Output:
`Global well-posedness for the mass-critical stochastic nonlinear Schrödinger equation on $R$: small initial data`

Expected output:
`Global well-posedness for the mass-critical stochastic nonlinear Schrödinger equation on $\mathbb{R}$: small initial data`

**Comment by furutaka** [comment]
I think you can get what you want by doing:
` encoder = LatexNodes2Text(keep_inline_math=True, keep_comments=True)`
`print encoder.latex_to_text(r'Global well-posedness for the mass-critical stochastic nonlinear Schr\"{o}dinger equation on $\mathbb{R}$: small initial data',keep_inline_math=True)`

**Comment by phfaist** [comment]
@furutaka's comment is indeed the correct way to go (thanks for replying!). I'm closing this issue, reopen if there are any further problems.
