### ISSUE TITLE
LatexNodes2Text(keep_inline_math=True).latex_to_text(keep_inline_math=True) eats up spaces.

### ISSUE THREAD

**Issue by furutaka** [phfaist/pylatexenc#15]
> [furutaka@Furutaka-3 automate-refs]$ conda list|grep pylatexenc
> pylatexenc                1.2                       <pip>
> [furutaka@Furutaka-3 automate-refs]$ python
> Python 2.7.14 |Anaconda, Inc.| (default, Dec  7 2017, 17:05:42) 
> [GCC 7.2.0] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> \>\>\> from pylatexenc.latex2text import LatexNodes2Text
> \>\>\> print (LatexNodes2Text(keep_inline_math=True).latex_to_text(r"$\alpha$ $\beta$  $\gamma$",keep_inline_math=True))    
> $\alpha$$\beta$$\gamma$
> \>\>\> print (LatexNodes2Text(keep_inline_math=True).latex_to_text(r"$\gamma$ detector",keep_inline_math=True))
> $\gamma$ detector
> \>\>\> print (LatexNodes2Text(keep_inline_math=True).latex_to_text(r"$\gamma$ $\gamma$ coincidence",keep_inline_math=True))
> $\gamma$$\gamma$ coincidence

**Comment by phfaist** [comment]
Fixed by my [latest commits](https://github.com/phfaist/pylatexenc/commit/f0baec105395be7889160d53c4d9a6018ca20bd5) today, based on the code in #16.
