### ISSUE TITLE
Caret not in utf8latexmap file

### ISSUE THREAD

**Issue by skikd636** [phfaist/pylatexenc#20]
When using the software I found that the caret (^) character was not being escaped by the UTF8tolatex function.  It seems it not in the _utf8latexmap file.

To "fix" this I monkey patched the utf82latex array with:

0x005E: r'\textasciicircum'

Not sure that was the correct symbol to use but it fixed my issie.

**Comment by phfaist** [comment]
Thanks, fixed.
