### ISSUE TITLE
Creating a conda-forge feedstock

### ISSUE THREAD

**Issue by milljm** [phfaist/pylatexenc#29]
Hello devs!

I am in the process of creating a conda-forge/pylatexenc-feedstock for this library. Thought I would mention my intentions. Feel free to close, or discuss concerns etc.

Cheers!

**Comment by phfaist** [comment]
cool, thanks!

**Comment by milljm** [comment]
So far the work being done to have this enter conda-forge is here: https://github.com/conda-forge/staged-recipes/pull/10418

Cheers!

**Comment by milljm** [comment]
Okay, its been merged:

https://github.com/conda-forge/pylatexenc-feedstock

Cheers!
