### ISSUE TITLE
Wrong reference to nodelist_to_latex func.

### ISSUE THREAD

**Issue by Sinclert** [phfaist/pylatexenc#35]
### Issue

The [apply_simplify_repl](https://github.com/phfaist/pylatexenc/blob/master/pylatexenc/latex2text/__init__.py#L1095) function within the `LatexNodes2Text` object references a non-existing function with the name `self.nodelist_to_latex`.

The issue only appears when parsing a document with the "%" character, as the only references to that non-existing function are within an `if "%" in simplify_repl` block.

### Proposal

There is already a [nodelist_to_latex](https://github.com/phfaist/pylatexenc/blob/master/pylatexenc/latexwalker/__init__.py#L2355) function defined on the `latexwalker/__init__.py` file.

A simple fix would be to replace:
```python
self.nodelist_to_latex
```

By:
```python
latexwalker.nodelist_to_latex
```

### Testing

I have tried to parse [this ArXiV paper](https://arxiv.org/e-print/cond-mat/9301005v1) by calling `LatexNodes2Text.latex_to_text` function before and after the fix.

Where before it crashed, now it does not.

**Comment by phfaist** [comment]
Thanks for noticing this. It looks like the bug only affected certain environments and went unnoticed until now. The method call should have been "self.nodelist_to_text", not "self.nodelist_to_latex". Fixed, will be included in next release.
