### ISSUE TITLE
mathbb symbols in .latex_to_text

### ISSUE THREAD

**Issue by ischurov** [phfaist/pylatexenc#40]
Hi, first of all, thanks a lot for this project! I found it very useful to quickly insert unicode characters that correspond to usual mathematical symbols in emails, etc.

Am I correct that there is no support for symbols like $\mathbb R$ in `.latex_to_text`? I see that appropriate records are included into `latexencode/_uni2latexmap.py`, e.g.

```
pylatexenc/latexencode/_uni2latexmap.py:0x1D549: r'\ensuremath{\mathbb{R}}',              # MATHEMATICAL DOUBLE-STRUCK CAPITAL R
```
but it appears they are not used in `latex_to_text`:

```python
from pylatexenc.latex2text import LatexNodes2Text
import unicodedata
R = LatexNodes2Text().latex_to_text(r"$\mathbb{R}$")
unicodedata.name(R)
# 'LATIN CAPITAL LETTER R'
```

Is it possible to add them? Unfortunately, I wasn't able to understand how to add new macros in  `.latex_to_text`.

**Comment by phfaist** [comment]
Hi, thanks for your interest. That's correct, `\mathbb{R}` worked in the unicode → latex direction but not the other way around. I just pushed a commit that should make the `\mathbb` macro work (along with friends `\mathit`, `\mathsf`, etc.). It will be included in the next release.
