### ISSUE TITLE
\le, \ge, \leqslant and \geqslant produce incorrect symbols

### ISSUE THREAD

**Issue by ischurov** [phfaist/pylatexenc#41]
I'm not sure if it is intentional or not, but currently `\le` and `\ge` are rendered as `<` and `>`. However, accoding to their LaTeX meaning, they have to be rendered as `≤` and `≥`. Also, `\leqslant` and `\geqslant` can (and probably should) be rendered as `⩽` and `⩾`.

**Comment by phfaist** [comment]
thanks for spotting this and for the fix.
