### ISSUE TITLE
missing braces after macro

### ISSUE THREAD

**Issue by tsgit** [phfaist/pylatexenc#44]
Hi,

the Polish ł is not properly protected with the option 
`replacement_latex_protection='braces-after-macro'`

```
In [1]: from pylatexenc.latexencode import unicode_to_latex                                                                                   

In [2]: unicode_to_latex('Jabłoński', replacement_latex_protection='braces-after-macro')                                                      
Out[2]: "Jab\\lo\\'nski"
```

it should be `"Jab\\l{}o\\'nski"`. This is with `pylatexenc==2.7`

Thanks for this very useful package
T.

**Comment by phfaist** [comment]
Thanks for spotting this, it should be fixed now.
