### ISSUE TITLE
Missing space in latex_to_text

### ISSUE THREAD

**Issue by malicialab** [phfaist/pylatexenc#46]
Hi there,
When processing BibTex files, I am seeing cases where latex_to_text incorrectly removes some spaces. Here is an example:

Python 3.5.2 (default, Oct  7 2020, 17:19:02) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pylatexenc.latex2text import LatexNodes2Text
>>> s = "{B}uilding an {E}fficient {C}omponent for {OCL} {E}valuation"
>>> LatexNodes2Text().latex_to_text(s)
'Building an Efficient Component for OCLEvaluation'

Note that "OCLEvaluation" should be "OCL Evaluation"

I can provide more examples if needed

**Comment by phfaist** [comment]
Hi, thanks for your issue report.

Are you seeing this problem with a recent version of pylatexenc (specifically ≥ 2.6)? With the latest version 2.8 I get the desired behavior.

The way `latex2text` handles spaces can be set with the `strict_latex_spaces=` option in `LatexNodes2Text`. For old versions of pylatexenc, the value of this option was 'based-on-source' by default (for legacy reasons mostly). If you're stuck with an old version of pylatexenc, you can set the option to `True` manually:
```
>>> latex2text.LatexNodes2Text(strict_latex_spaces=True).latex_to_text('{B}uilding an {E}fficient {C}omponent for {OCL} {Evaluation}')
'Building an Efficient Component for OCL Evaluation'
```

I'm closing the issue, feel free to reopen if the issue remains unresolved for you.
