### ISSUE TITLE
LatexGroupNode Parse uncorrect

### ISSUE THREAD

**Issue by xiejianping0108** [phfaist/pylatexenc#47]
`w = LatexWalker(r"""
... \documentclass[twoside]{article}
...\usepackage{amsmath,amssymb}
...\usepackage{amsthm}

...\usepackage{graphicx,epsfig,amscd,mathrsfs,multirow,bm}

...\usepackage{cite}%引用宏包

...\input xy
...\xyoption{all}
...\input scrload.tex
...\allowdisplaybreaks[4]%多行公式换页从0到4，表示分页的坚决程度,例如0表示能不分页就不分页,4表示强制分页。

%------------------------ Page Format --------------------------
...\textwidth=147truemm
...\textheight=210truemm
...\headsep=4truemm
...\topmargin= 0pt
...\oddsidemargin=0pt
...\evensidemargin=0pt
...\parindent=16pt
...\setcounter{page}{415}

...\footskip=0pt
...\renewcommand{\baselinestretch}{1.06}
...\renewcommand{\arraystretch}{1.2}
...\catcode`@=11
...\long\def\@makefntext#1{\noindent #1}
...\newskip\tabcentering \tabcentering=1000pt plus 1000pt minus 1000pt
...\def\REF#1{\par\hangindent\parindent\indent\llap{#1\enspace}\ignorespaces} %reference format
...\def\MCH#1#2{\setbox0=\hbox{\raise#1\hbox{#2}}\smash{\box0}}% move char
...\def\sub#1{\par\vspace{\baselineskip}\noindent #1\vspace*{\baselineskip}\rm\par}
...\def\CR{\cr\noalign{\vspace{1mm} \hrule \vspace{1mm}}}
...\def\@evenfoot{}\def\@oddfoot{}

...\def\@evenhead{\hbox to\textwidth{\small\rm\thepage \hfill
...{\it Yu-e BAO, Na LI and Linfen ZHANG}}} % authors name (the given name is before the surname, and use "and" to separate two authors)%

...\def\@oddhead{\hbox to \textwidth{\small{\it
...Differentiability of interval valued function and its application in interval valued programming
...} \hfill\thepage}}   % Capitalize the first letter in abbreviate title%

...%format defination
...\def\scr{\mathscr}
...\def\SUB#1{\vskip .2in\leftline{\large\bf #1}\vskip .1in}
...\def\subsec#1{\vskip 2mm\leftline{#1}\vskip 1mm}
...\def\th#1{\vskip 1mm\noindent{\bf #1}\quad}
...\def\thn#1{\noindent{\bf #1}\quad}
...\def\proofn{\noindent{\it Proof}\quad}
...\def\proof{\vskip 1mm\noindent{\it Proof}\quad}
...\def\vsp{\vskip {1mm}}
...%end format defination

...\font\tenbf=cmb10 scaled \magstep0
...\font\tenrm=cmr10 scaled \magstep0
...\def\ESEC#1#2#3{\vskip.2in \begin{center} \tenbf #1\\[.1in]
...\small #2\\
...\footnotesize $($#3$)$\\[.1in]
...\end{center}}

...\renewcommand{\topfraction}{1}
...\renewcommand{\bottomfraction}{1}
...\renewcommand{\textfraction}{0}
...\renewcommand{\floatpagefraction}{0}
...\floatsep=0pt
...\textfloatsep=0pt
...\intextsep=0pt
...\catcode`@=12

...**\def\bc{\begin{center}}**
...\def\ec{\end{center}}
...\def\no{\noindent}
...\def\hang{\hangindent\parindent}
...\def\textindent#1{\indent\llap{\qquad #1\ \ \enspace}\ignorespaces}
...\def\ref{\par\hang\textindent}

...\def\d#1#2{\frac{\displaystyle #1}{\displaystyle #2}}
...\def\f#1#2{\frac{#1}{#2}}

...\def\d{{\rm d}}

...%\usepackage{lineno}

...\begin{document}

...%\linenumbers

...\abovedisplayskip=6pt plus 1pt minus 1pt \belowdisplayskip=6pt
...plus 1pt minus 1pt
...%-------------------  First Head  -----------------------------------------
...\thispagestyle{empty} \vspace*{-1.0truecm} \noindent
...\parbox[b]{7truecm}{\footnotesize\baselineskip=11pt\noindent{\it Journal of Mathematical Research with Applications}\\
...Jul., 2020, Vol.\,40, No.\,4, pp.\,415--431\\
...DOI:10.3770/j.issn:2095-2651.2019.04.009\\
...Http://jmre.dlut.edu.cn} \hfill
...%\parbox[]{6truecm}{\vskip -1.7cm \hfill \begin{tabular}{l}\\\hline {\bf Journal of Mathematical}\\ {\bf Research and Exposition}\\\hline\end{tabular}}
...%\parbox[t]{6truecm}{\vskip -1.7cm \hfill\includegraphics{actmark.eps}}
...%===================Text=============================================
...\vskip 10mm \bc{\Large\bf Differentiability of Interval Valued Function and Its Application in Interval Valued Programming
...\footnotetext{\footnotesize Received February 20, 2019; Accepted April 21, 2020\\
...Supported by the National Natural Science Fund of China (Grant No.\,11461052) and the Natural Science Foundation of Inner Mongolia (Grant No.\,2018MS01010).\\
...* Corresponding author\\
...E-mail address: byebed@y163.com (Yu-e BAO); 1024951096@qq.com (Na LI); 1475094089@qq.com (Linfen ZHANG)
...} } \ec
...%国家自然科学基金(Grant No.11461052),内蒙古自然科学基金(Grant No.2018MS01010).

...\vskip 5mm
...\bc{\bf Yu-e BAO$^*$,\ \ \ Na LI,\ \ \ Linfen ZHANG}\\
...{\small\it College of Mathematics and Physics, Inner Mongolia University for Nationalities,\\ Inner Mongolia $028043$, P. R. China
...}\ec

...\vskip 1 mm
\end{document}`

Tex content as up follow, For this line "\def\bc{\begin{center}}" parse is uncorrect,  "\begin{center}" and back content is parse to  a LatexGroupNode, using version is v2.8.

**Comment by phfaist** [comment]
Hi, thanks for your feedback. `pylatexenc.latexwalker` will attempt to parse LaTeX with a simplified set of rules, it's not a full TeX engine. The idea is that it parses LaTeX content as marked up text, and does not have a state engine that would be needed for ``\newcommand`` and ``\def`` instructions to work. I've been thinking about trying to provide limited support for ``\newcommand`` and ``\def`` instructions, but that would require some deeper changes in the latexwalker engine. The supported alternative is to use `latexwalker` only to parse the body of the document, and to manually provide any definitions with replacement text for custom commands (see https://pylatexenc.readthedocs.io/en/latest/latex2text/#custom-latex-conversion-rules-a-simple-template for instance).

In a side project of mine, I tried to add minimal support for ``\newcommand``-type instructions (see https://github.com/phfaist/latexpp and https://latexpp.readthedocs.io/en/latest/fixes/#latexpp.fixes.newcommand.Expand) and it's based on `pylatexenc`, but I'd consider that still very much at an experimental stage.
