### ISSUE TITLE
Greek letters \iota and \epsilon in unicode_to_latex()

### ISSUE THREAD

**Issue by crazyTeXer** [phfaist/pylatexenc#51]
Thank you very much for this project! It is really helpful.

Could you please fix a couple of bugs related to the Greek letters?

For ι (Greek small letter iota, `U+03B9`), function `unicode_to_latex()` gives `\ensuremath{\i}`. However, this is incorrect. It should be `\ensuremath{\iota}` instead.

For ϵ (Greek lunate epsilon symbol, `U+03F5`), function `unicode_to_latex()` gives nothing but it should be `\ensuremath{\epsilon}`.

Source: Table 188 in [The Comprehensive LaTeX Symbol List (PDF)](https://mirror.truenetwork.ru/CTAN/info/symbols/comprehensive/symbols-a4.pdf).

**Comment by phfaist** [comment]
Thanks for spotting these issues, fixed in latest commit.
