### ISSUE TITLE
Problems with multiple unicodes

### ISSUE THREAD

**Issue by francescovallone** [phfaist/pylatexenc#63]
Hello,
I have an html page with some math formulas that I want to transform in latex functions. But for a lot of unicode characters it returns this error:
There is a way to convert even these unicode characters?
<details>
  <summary>Logs</summary>
  No known latex representation for character: U+E683 - ‘’
</details>
</br>
Here is the code I'm using.
```python
# obj is a BeautifulSoup Element
print(f'<{header} style="margin: 0; font-weight: normal; font-size: {value}px;" class="ff5">{unicode_to_latex(obj.text)}</{header}>)
```

Sorry for bothering you and thanks for helping me.

**Comment by phfaist** [comment]
Hi, thanks for the feedback. As I'm sure you know Unicode has a *lot* of characters (see https://www.unicode.org/charts/), and not all of them have LaTeX counterparts. I've tried to assemble a collection of unicode character codes with their LaTeX code counterparts, from various sources, and hard-coded it for use by the `latexencode` python module. The list isn't exhaustive but should cover a wide range of use cases.

But there are many unicode characters that don't have a LaTeX equivalent. More importantly, finding all unicode characters that do have a LaTeX equivalent is a very tedious task. At this point I'm relying on adding characters that people spot are missing, and I don't plan on systematically analyzing unicode charts and finding LaTeX equivalents.

If you spot unicode characters that have a LaTeX equivalent, and that are not supported by `latexencode`, feel free to contribute them!

I'm closing this issue, feel free to re-open it (or open new specific issues) if you provide a list of unicode characters with LaTeX equivalents that `latexencode` doesn't support.
