### ISSUE TITLE
Special characters treated as macros

### ISSUE THREAD

**Issue by johansmolinski** [phfaist/pylatexenc#73]
Special characters escaped by \, for instance \$ or \#, are treated as macro nodes. Is this on purpose? In my opinion they should just be replaced by corresponding characters ($ respectively #) and be treated like character nodes (or be included in the current character node if one is already opened).

**Comment by phfaist** [comment]
Yes, they are macros. E.g., you can redefine them in TeX/LaTeX; you can try for instance:
```tex
\renewcommand\#{phone number}
My \# is 012 345 6789.
```

*Pylatexenc* reflects the behavior of TeX/LaTeX by treating `\#`, `\$`, etc., as macros, as well. This is much more flexible than simply replacing them by corresponding characters, and would avoid a special treatment of a special kind of macros. In any case, you can walk through your node tree and replace these macro nodes by corresponding character nodes, if you need these elements to be treated as characters.

Is there a use case where generating a macro node for `\#`, `\$`, etc. is problematic?

I'm closing for now, feel free to reopen if I'm missing something.
