### ISSUE TITLE
various upgrades

### ISSUE THREAD

**Issue by nschloe** [phfaist/pylatexenc#78]
pylatexenc's code base is historically grown and could require a facelift or two. With your permission, I'd provide a couple or PRs for that. (You can still decline them of course.)

I'm thinking [black](https://github.com/psf/black), [pyupgrade](https://github.com/asottile/pyupgrade) etc.

**Comment by phfaist** [comment]
I'm working on a new version of pylatexenc and so I have been going over the code base over the past months. One of the features I insist on keeping is compatibility with old code, and I want to keep supporting older versions of python as much as reasonably possible so as not to unnecessarily break old setups. (Some people can be stuck to old software versions for various reasons often beyond their control; say a lab computer with specific hardware that needs a specific old version of an OS, for which there is no new python build, etc. If such a setup happened to use my code, I don't want my package to break their setup.) So I'm planning to be conservative in how the code is upgraded.

I see you've submitted a few issues with your suggestions, I'll go through them and provide some comments. Some of the features you're suggesting are indeed already planned in the development version for the upcoming v3 version of pylatexenc.
