### ISSUE TITLE
how to instantiate LatexMacroNode?

### ISSUE THREAD

**Issue by nschloe** [phfaist/pylatexenc#79]
I'm trying to change 
```latex
{\it text}
```
to
```latex
\textit{text}
```
with pylatexenc. To this end, I need create a `LatexMacroNode` from a `LatexGroupNode`. I tried
```python
new_node = LatexMacroNode("textit", nodeargd=groupnode.nodelist[1:])
print()
print("xx", new_node)
print(nodelist_to_latex([new_node]))
```
but this fails with
```
AttributeError: 'list' object has no attribute 'argspec'
```
I'n not sure how to properly instantiate `LatexMacroNode`

**Comment by nschloe** [comment]
I think I got it:
```python
new_node = LatexMacroNode(
    macroname="textit",
    nodeargd=ParsedMacroArgs(
        argspec="{",
        argnlist=[LatexGroupNode(nodelist=node.nodelist[1:])],
    ),
)
```

**Comment by phfaist** [comment]
The function `nodelist_to_latex()` should not be relied upon. See my comment in #89. I'm hoping to add the ability to regenerate latex code from a node's properties in the future. In the meantime, my sister project [latexpp](https://github.com/phfaist/latexpp) might provide an alternative.
