### ISSUE TITLE
Support for symbols < and >

### ISSUE THREAD

**Issue by luiscruz** [phfaist/pylatexenc#9]
Although symbols `<` and `>` do not to be changed that need to be encapsulated with `\ensuremath{}`.

PS: Your library is being very helpful in a small project oI am working on. Thanks!

**Comment by phfaist** [comment]
Hi, thanks for your feedback.

I'm not sure why exactly you would like to encode the `<` and `>` characters. They are valid in LaTeX as well... could you be a little more specific?

If you would like to change the way `pylatexenc.latexencode` works to do something special for some characters, you can always edit the dictionary `pylatexenc.latexencode.utf82latex`, for instance:
```
>>> pylatexenc.latexencode.utf82latex[ord('<')] = r'\ensuremath{\langle}' # or whatever you like
>>> pylatexenc.latexencode.utf82latex[ord('>')] = r'\ensuremath{\rangle}'
>>> print(pylatexenc.latexencode.utf8tolatex('Symbols < and > get encoded'))
Symbols {\ensuremath{\langle}} and {\ensuremath{\rangle}} get encoded
```

This module is anyway pretty basic, it only does character-by-character substitution, so for instance you can't handle `...` ⟶ `\ldots` and so on.  Perhaps one day I'll update the algorithm to something better (you're welcome to contribute—feel free to send me a pull request).

**Comment by phfaist** [comment]
Ah now I understand your original issue, that the '<' and '>' characters need to be protected with `\ensuremath{<}`. Apologies, fixing that now.
