### ISSUE TITLE
Exception when parsing macro definitions with multiple arguments

### ISSUE THREAD

**Issue by dspinellis** [phfaist/pylatexenc#96]
The definition `\def\href#1#2{#2}` (extracted from the BibTeX output file), will cause pylatexenc 2.10 and 3.0a14 to throw an `IndexError` exception in `_defaultspecs.py", line 194, in <lambda> '{} <{}>'.format(l2tobj.nodelist_to_text([n.nodeargd.argnlist[1]])`.

**Comment by phfaist** [comment]
See #83. `\def` is a command with a complex argument structure and it is not yet supported. Currently, you need to write your own argument parser for it if you'd like to parse such constructs. I am hoping to also provide a arguments parser for commands such as `\def` in pylatexenc v3, but haven't gotten to it yet.
